server:
  port: 9094

spring:
  profiles:
    active: dev
  application:
    name: order

app:
  service:
    url: "http://userservice/user/fetchUserById/"
#  cors:
#    allowed-origins: "http://localhost:4200"
#    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
#    allowed-headers: "*"
#    allow-credentials: true

