server:
  port: 9084

spring:
  profiles:
    active: local
  application:
    name: order

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 120000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5

    consumer:
      group-id: order-ms
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer #org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer #org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.codecode.order.dto,com.codecode.core.*"
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
      isolation-level: READ_COMMITTED

app:
  service:
    url: "http://userservice/user/fetchUserById/"
  kafka:
    request-topic: "fetch-user-request"
    reply-topic: "fetch-user-reply"
    order-event-topic: "order-event"
    food-command-topic: "food-command"
    food-event-topic: "food-event"
    payment-command-topic: "payment-command"
    payment-event-topic: "payment-event"

#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.springframework.kafka.listener.ConcurrentMessageListenerContainer: INFO
logging:
  level:
    org.springframework.kafka.transaction.KafkaTransactionManager: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.apache.kafka.clients.producer.internals.TransactionManager: DEBUG



