eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      host: localhost
      port: 27071
      database: orderdb
      repositories:
        enabled: true

#spring:
#  mongodb:
#    uri: mongodb+srv://admin:admin123456@atlas-cluster.9ghj1qt.mongodb.net/orderdb?retryWrites=true&w=majority
#    host: atlas-cluster.9ghj1qt.mongodb.net
#    database: orderdb
