server:
  port: 9081

spring:
  profiles:
    active: local

  application:
    name: restaurantlisting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 120000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        enable:
          idempotence: true
          max:
            in:
              flight:
                requests:
                  per:
                    connection: 5

    consumer:
      # 1. Set the top-level deserializers to the ErrorHandlingDeserializer wrapper
      group-id: foodcatalogue-service-restaurantid-consumer
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer #org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer #org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.codecode.restaurantlisting.dto"
          # 2. Define the actual delegate deserializers that do the real work
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer

#app:
#  cors:
#    allowed-origins: "http://localhost:4200"
#    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
#    allowed-headers: "*"
#    allow-credentials: true

