server:
  port: 9082

spring:
  profiles:
    active: local
  application:
    name: foodcatalogue-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 120000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection: 5
#      transaction-id-prefix: foodcatalogue-service-${random.value}-

    consumer:
      group-id: foodcatalogue-ms
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer #org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer #org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.codecode.core.*"
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer

app:
  service:
    url: http://restaurantlisting/restaurant/fetchById/
  kafka:
    food-command-topic: "food-command"
    food-event-topic: "food-event"

logging:
  level:
    org.springframework.kafka.transaction.KafkaTransactionManager: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.apache.kafka.clients.producer.internals.TransactionManager: DEBUG

